create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table project (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, user_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKc59x6m17pigwol0ykd3db06ic foreign key (user_id) references user (id);
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case_crc_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case_crc_link add constraint FKdtg14hk5ywl6wlug62lbt6wi4 foreign key (crc_id) references crc (id);
alter table use_case_crc_link add constraint FKl1mevet2v0b8xi2cyy7kivki3 foreign key (use_case_id) references use_case (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case_crc_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case_crc_link add constraint FKdtg14hk5ywl6wlug62lbt6wi4 foreign key (crc_id) references crc (id);
alter table use_case_crc_link add constraint FKl1mevet2v0b8xi2cyy7kivki3 foreign key (use_case_id) references use_case (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case_crc_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case_crc_link add constraint FKdtg14hk5ywl6wlug62lbt6wi4 foreign key (crc_id) references crc (id);
alter table use_case_crc_link add constraint FKl1mevet2v0b8xi2cyy7kivki3 foreign key (use_case_id) references use_case (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case_crc_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case_crc_link add constraint FKdtg14hk5ywl6wlug62lbt6wi4 foreign key (crc_id) references crc (id);
alter table use_case_crc_link add constraint FKl1mevet2v0b8xi2cyy7kivki3 foreign key (use_case_id) references use_case (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table alternativ_flow (id integer not null auto_increment, use_case_id integer, description varchar(255), primary key (id)) engine=InnoDB;
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table alternativ_flow add constraint FK76ij6qe3cfx14qqnthwni0b1a foreign key (use_case_id) references use_case (id);
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table alternativ_flow (id integer not null auto_increment, use_case_id integer, description varchar(255), primary key (id)) engine=InnoDB;
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table alternativ_flow add constraint FK76ij6qe3cfx14qqnthwni0b1a foreign key (use_case_id) references use_case (id);
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table alternativ_flow (id integer not null auto_increment, use_case_id integer, description varchar(255), primary key (id)) engine=InnoDB;
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table alternativ_flow add constraint FK76ij6qe3cfx14qqnthwni0b1a foreign key (use_case_id) references use_case (id);
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
create table alternativ_flow (id integer not null auto_increment, use_case_id integer, description varchar(255), primary key (id)) engine=InnoDB;
create table crc (id integer not null auto_increment, project_id integer, class_name varchar(255), collaborations varchar(255), responsibilties varchar(255), primary key (id)) engine=InnoDB;
create table crc_use_case_link (crc_id integer not null, use_case_id integer not null) engine=InnoDB;
create table project (id integer not null auto_increment, user_id integer, project_name varchar(255), primary key (id)) engine=InnoDB;
create table use_case (id integer not null auto_increment, project_id integer, actor varchar(255), main_flow varchar(255), postconditions varchar(255), preconditions varchar(255), use_case_name varchar(255), primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table alternativ_flow add constraint FK76ij6qe3cfx14qqnthwni0b1a foreign key (use_case_id) references use_case (id);
alter table crc add constraint FKd1jaucbdft7192tt7y1mckxq4 foreign key (project_id) references project (id);
alter table crc_use_case_link add constraint FKc3ucyhcikhy1umh4652ce0toy foreign key (use_case_id) references use_case (id);
alter table crc_use_case_link add constraint FKlcg4dpdncib52pmnf177nn0ar foreign key (crc_id) references crc (id);
alter table project add constraint FKo06v2e9kuapcugnyhttqa1vpt foreign key (user_id) references user (id);
alter table use_case add constraint FKk194p8v5b00xq2wx9kcyae01k foreign key (project_id) references project (id);
